security:
    role_hierarchy:
        ROLE_MANAGER_STALINGRAD: []
        ROLE_MANAGER_CATHERINE: []
        ROLE_MANAGER_IVAN: []
        ROLE_MANAGER_URSS: []
        ROLE_MANAGER_ANASTASIA: []
        ROLE_MANAGER_RASPOUTINE: []
        ROLE_ADMIN: [ROLE_MANAGER_STALINGRAD, ROLE_MANAGER_CATHERINE, ROLE_MANAGER_IVAN, ROLE_MANAGER_URSSS, ROLE_MANAGER_ANASTASIA, ROLE_MANAGER_RASPOUTINE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    password_hashers:
        # auto hasher with default options for the User class (and children)
        App\Entity\User: 'auto'

        # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_id: authenticate
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
                success_handler: App\Security\AuthenticationSuccessHandler
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    access_control:
        - {path: ^/super/admin, roles: ROLE_SUPER_ADMIN}
        - { path: ^/admin, roles: ROLE_ADMIN }
        - {path: ^/manager/stalingrad, roles: ROLE_MANAGER_STALINGRAD}
        - {path: ^/manager/catherine, roles: ROLE_MANAGER_CATHERINE}
        - {path: ^/manager/ivan, roles: ROLE_MANAGER_IVAN}
        - {path: ^/manager/urss, roles: ROLE_MANAGER_URSS}
        - {path: ^/manager/anastasia, roles: ROLE_MANAGER_ANASTASIA}
        - {path: ^/manager/raspoutine, roles: ROLE_MANAGER_RASPOUTINE}
        - { path: ^/dashboard, roles: ROLE_USER }
