twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        allMenus: '@App\Service\MenuService'

when@test:
    twig:
        strict_variables: true
