controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
app_homepage:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: fr|en|es # Liste des langues supportées
    defaults:
        _locale: fr
